name: Quarto to gh-pages
on:
  push: { branches: [ master ] }
  workflow_dispatch:

permissions:
  contents: write   # needed to push to gh-pages

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # minimal system libs for sf/s2
      - name: Install GIS libs
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libudunits2-dev libgdal-dev libgeos-dev libproj-dev gdal-bin \
            cmake build-essential pkg-config

      - uses: r-lib/actions/setup-renv@v2

      # This single step renders AND pushes to gh-pages
      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
